apiVersion: v1
kind: Namespace
metadata:
  name: odoo-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: odoo-production
  labels:
    environment: production
